/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/222.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-3.113, 0.003, 0]} scale={[0.024, 0.033, 0.024]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials["100 dollars.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials["elastic.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/222.glb");
