/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, OrthographicCamera } from "@react-three/drei";

export function SmallBagModel(props) {
  const { nodes, materials } = useGLTF("/small_bag.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <OrthographicCamera
          makeDefault={false}
          far={50000}
          near={0}
          position={[565.965, 550.966, 577.066]}
          rotation={[-Math.PI / 4, 0.615, Math.PI / 6]}
        >
          <directionalLight
            intensity={0.75}
            decay={2}
            rotation={[-0.7, 0.648, 0.949]}
          />
        </OrthographicCamera>
        <group scale={0.75}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bag.geometry}
            material={nodes.bag.material}
            position={[0.053, 24.518, 0.401]}
            scale={[0.779, 1, 0.199]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.handle_back.geometry}
            material={nodes.handle_back.material}
            position={[-0.486, 88.511, -110.189]}
            rotation={[-3.057, -0.034, -1.571]}
            scale={[1.35, 1.182, 1.222]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.handle_front.geometry}
            material={nodes.handle_front.material}
            position={[-0.56, 88.511, 111.399]}
            rotation={[-0.085, -0.037, -1.569]}
            scale={[-1.35, 1.182, 1.222]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ring_front_left.geometry}
            material={nodes.ring_front_left.material}
            position={[-73.987, 225.883, 74.254]}
            rotation={[1.503, 0, 0.004]}
            scale={1.069}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ring_front_right.geometry}
            material={nodes.ring_front_right.material}
            position={[73.3, 225.881, 74.746]}
            rotation={[1.503, 0, 0.004]}
            scale={1.069}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ring_back_left.geometry}
            material={nodes.ring_back_left.material}
            position={[-74.043, 225.883, -73.303]}
            rotation={[1.639, 0, -Math.PI]}
            scale={[-1.069, 1.069, 1.069]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ring_back_right.geometry}
            material={nodes.ring_back_right.material}
            position={[73.244, 225.881, -73.278]}
            rotation={[1.639, 0, -Math.PI]}
            scale={[-1.069, 1.069, 1.069]}
          />
          <group position={[-74.117, 225.884, 71.033]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus_2.geometry}
              material={nodes.Torus_2.material}
              position={[-0.005, 1.208, -0.659]}
              rotation={[-0.564, 0.888, 0.039]}
              scale={[-0.1, 0.072, 0.108]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus.geometry}
              material={nodes.Torus.material}
              position={[0, -1.4, 0.564]}
              rotation={[2.529, 1.031, 2.053]}
              scale={[-0.077, 0.101, 0.117]}
            />
          </group>
          <group position={[72.448, 225.813, 71.907]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus_2_1.geometry}
              material={nodes.Torus_2_1.material}
              position={[1.54, 0, -0.415]}
              rotation={[0.426, 0.272, -1.454]}
              scale={[-0.1, 0.072, 0.108]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus_1.geometry}
              material={nodes.Torus_1.material}
              position={[-1.166, -0.898, 0]}
              rotation={[1.793, 0.26, 3.026]}
              scale={[-0.077, 0.101, 0.117]}
            />
          </group>
          <group position={[-74.182, 225.884, -70.076]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus_2_2.geometry}
              material={nodes.Torus_2_2.material}
              position={[-0.009, 1.208, 0.652]}
              rotation={[-2.559, 0.891, 3.099]}
              scale={[0.1, 0.072, 0.108]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus_2.geometry}
              material={nodes.Torus_2.material}
              position={[0, -1.4, -0.57]}
              rotation={[0.293, 0.954, 1.672]}
              scale={[0.077, 0.101, 0.117]}
            />
          </group>
          <group position={[72.371, 225.813, -70.446]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus_2_3.geometry}
              material={nodes.Torus_2_3.material}
              position={[1.551, 0, 0.425]}
              rotation={[2.716, 0.275, -1.687]}
              scale={[0.1, 0.072, 0.108]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus_3.geometry}
              material={nodes.Torus_3.material}
              position={[-1.153, -0.898, 0]}
              rotation={[1.336, 0.26, 0.117]}
              scale={[0.077, 0.101, 0.117]}
            />
          </group>
        </group>
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[565.965, 550.966, 577.066]}
          rotation={[-Math.PI / 4, 0.615, Math.PI / 6]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/small_bag.glb");
